# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurantlocation_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantlocation',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
